name: 'Build Model Manifest'
description: 'Generates a package model from partials and a manifest of git commit hashes of that model.'
inputs:
  common-model-path:
    description: 'Path to baseline model file.'
    required: true
    default: ./baseline-model.json
  custom-model-path:
    description: 'Path to customization model file.'
    required: true
    default: ./custom-model.json
  generated-manifest-path:
    description: 'Path to manifest file to be generated.'
    required: true
    default: ./generated-manifest.txt
  generated-model-path:
    description: 'Path to model file to be generated.'
    required: true
    default: /tmp/generated-model.json
runs:
  using: "composite"
  steps:
    - id: generate-model
      name: Generate Model
      run: |
        jq -s '.[0] * .[1]' ${{ inputs.common-model-path }} ${{ inputs.custom-model-path }} > ${{ inputs.generated-model-path }}
        echo "Generated model:"
        cat ${{ inputs.generated-model-path }}
      shell: bash
    - id: generate-manifest
      name: Generate Manifest
      run: |
        [ -e ${{ inputs.manifest-path }} ] && rm ${{ inputs.manifest-path }}
        cat /tmp/model.json | ${{ github.action_path }}/build-manifest.sh ./manifest-raw.txt /tmp/manifest
        sort ./manifest-raw.txt > ${{ inputs.manifest-path }}
        rm ./manifest-raw.txt
        echo "Generated manifest:"
        cat ${{ inputs.manifest-path }}
      shell: bash